---
title: "Alternative HW using dplyr package"
author: "Lilik Pranowo"
date: "March 22, 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Data manipulation

Load "dplyr" and "tidyr" packages
```{r echo= TRUE, include= TRUE}
library(dplyr) 
library(tidyr)
```

Read data:
```{r}
dat <- read.csv("ArrestMini.csv")
dat<-na.omit(dat)
```

Create new variables: "DATE" and "TIME" from variables "ARRESTTIME" then save it to "dat1" dataframe
```{r}
dat1 <- dat %>% 
  separate(ARRESTTIME, c('DATE', 'TIME'), sep = 'T')
```

```{r echo=FALSE}
head (dat1)
```

Aggregate council districts that is affected by crime on the day --> I save it as "Arrest_Daily"
```{r}
Arrest_Daily <- dat1 %>%
  group_by(DATE) %>%
  summarize(CASES = n(), NUM_COUNCIL = n_distinct(COUNCIL_DISTRICT)) %>%
  arrange(DATE) 
```

```{r echo=FALSE}
Arrest_Daily
```



## Plots
Plot the number of council districts that reports at least one arrest for each day:

```{r}
rdate <- as.Date(Arrest_Daily$DATE, "%Y-%m-%d")
```

```{r}
plot(Arrest_Daily$NUM_COUNCIL~rdate, type="l", col="red", xlab="Time",ylab="Numb of Council Districts Having Crime", main="The Spread of Crime", lwd=1)
```

